import axiosInstance from "@/services/axios";
import type { PopularResponse } from "@/types/popular";
import type { MainResponse } from "@/types/main";

const USE_MOCK_MAIN = process.env.NEXT_PUBLIC_USE_MOCK_MAIN === "true";

const MOCK_MAIN: MainResponse = {
  result: "SUCCESS",
  data: {
    userCurations: [
      {
        id: 101,
        type: "POPUP",
        title: "감각적인 라이프스타일 팝업",
        subTitle: "취향 저격 셀렉션",
        thumbnail: "https://picsum.photos/seed/main-101/600/800",
        region: "서울 성수",
        place: "성수XYZ",
        startDate: "2026-02-10",
        endDate: "2026-03-01",
        category: ["팝업", "라이프스타일"],
        dDay: 11,
      },
      {
        id: 102,
        type: "EXHIBITION",
        title: "빛과 색의 현대미술전",
        subTitle: "몰입형 전시",
        thumbnail: "https://picsum.photos/seed/main-102/600/800",
        region: "서울 용산",
        place: "아트스페이스",
        startDate: "2026-02-01",
        endDate: "2026-03-15",
        category: ["전시", "현대미술"],
        dDay: 25,
      },
      {
        id: 103,
        type: "POPUP",
        title: "캐릭터 굿즈 페어",
        subTitle: "한정 굿즈 대공개",
        thumbnail: "https://picsum.photos/seed/main-103/600/800",
        region: "서울 홍대",
        place: "홍대입구역",
        startDate: "2026-02-14",
        endDate: "2026-02-28",
        category: ["팝업", "캐릭터"],
        dDay: 8,
      },
      {
        id: 104,
        type: "EXHIBITION",
        title: "사진으로 담은 도시",
        subTitle: "도시 기록 프로젝트",
        thumbnail: "https://picsum.photos/seed/main-104/600/800",
        region: "서울 종로",
        place: "세종문화회관",
        startDate: "2026-02-05",
        endDate: "2026-03-20",
        category: ["전시", "사진"],
        dDay: 30,
      },
      {
        id: 105,
        type: "POPUP",
        title: "디자이너 협업 팝업",
        subTitle: "리미티드 컬렉션",
        thumbnail: "https://picsum.photos/seed/main-105/600/800",
        region: "서울 강남",
        place: "가로수길",
        startDate: "2026-02-11",
        endDate: "2026-02-25",
        category: ["팝업", "패션"],
        dDay: 7,
      },
      {
        id: 106,
        type: "EXHIBITION",
        title: "일러스트 아카이브",
        subTitle: "신진 작가전",
        thumbnail: "https://picsum.photos/seed/main-106/600/800",
        region: "서울 성동",
        place: "성수 아트센터",
        startDate: "2026-02-08",
        endDate: "2026-03-12",
        category: ["전시", "일러스트"],
        dDay: 22,
      },
      {
        id: 107,
        type: "POPUP",
        title: "테크 체험 팝업",
        subTitle: "신제품 미리보기",
        thumbnail: "https://picsum.photos/seed/main-107/600/800",
        region: "서울 송파",
        place: "롯데월드몰",
        startDate: "2026-02-17",
        endDate: "2026-03-03",
        category: ["팝업", "테크"],
        dDay: 13,
      },
      {
        id: 108,
        type: "EXHIBITION",
        title: "디자인 오브제전",
        subTitle: "공간과 오브제",
        thumbnail: "https://picsum.photos/seed/main-108/600/800",
        region: "서울 마포",
        place: "홍대 갤러리",
        startDate: "2026-02-09",
        endDate: "2026-03-22",
        category: ["전시", "디자인"],
        dDay: 32,
      },
      {
        id: 109,
        type: "POPUP",
        title: "푸드 컬래버 팝업",
        subTitle: "한정 메뉴 출시",
        thumbnail: "https://picsum.photos/seed/main-109/600/800",
        region: "서울 마포",
        place: "연남동",
        startDate: "2026-02-13",
        endDate: "2026-02-27",
        category: ["팝업", "F&B"],
        dDay: 9,
      },
      {
        id: 110,
        type: "EXHIBITION",
        title: "회화의 재발견",
        subTitle: "컬렉터스 픽",
        thumbnail: "https://picsum.photos/seed/main-110/600/800",
        region: "서울 서초",
        place: "예술의전당",
        startDate: "2026-02-06",
        endDate: "2026-03-26",
        category: ["전시", "회화"],
        dDay: 36,
      },
    ],
    upcomingCurations: [
      {
        id: 201,
        type: "POPUP",
        title: "3월 오픈 예정 팝업",
        subTitle: "사전 예약 혜택",
        thumbnail: "https://picsum.photos/seed/upcoming-201/600/800",
        region: "서울 강남",
        place: "코엑스",
        startDate: "2026-03-05",
        endDate: "2026-03-20",
        category: ["팝업", "패션"],
        dDay: 15,
      },
      {
        id: 202,
        type: "EXHIBITION",
        title: "조각의 흐름전",
        subTitle: "사전 예매 중",
        thumbnail: "https://picsum.photos/seed/upcoming-202/600/800",
        region: "서울 서초",
        place: "예술의전당",
        startDate: "2026-03-10",
        endDate: "2026-04-10",
        category: ["전시", "조각"],
        dDay: 20,
      },
      {
        id: 203,
        type: "POPUP",
        title: "리빙 큐레이션 팝업",
        subTitle: "봄 시즌 한정",
        thumbnail: "https://picsum.photos/seed/upcoming-203/600/800",
        region: "서울 성수",
        place: "성수 언더스탠드",
        startDate: "2026-03-12",
        endDate: "2026-03-27",
        category: ["팝업", "라이프스타일"],
        dDay: 22,
      },
      {
        id: 204,
        type: "EXHIBITION",
        title: "미디어아트 특별전",
        subTitle: "사전 예약 오픈",
        thumbnail: "https://picsum.photos/seed/upcoming-204/600/800",
        region: "서울 중구",
        place: "DDP",
        startDate: "2026-03-08",
        endDate: "2026-04-05",
        category: ["전시", "미디어아트"],
        dDay: 18,
      },
      {
        id: 205,
        type: "POPUP",
        title: "봄 시즌 뷰티 팝업",
        subTitle: "예약 고객 사은품",
        thumbnail: "https://picsum.photos/seed/upcoming-205/600/800",
        region: "서울 강남",
        place: "삼성동",
        startDate: "2026-03-15",
        endDate: "2026-03-30",
        category: ["팝업", "뷰티"],
        dDay: 25,
      },
      {
        id: 206,
        type: "EXHIBITION",
        title: "사진전: 오래된 도시",
        subTitle: "아카이브 컬렉션",
        thumbnail: "https://picsum.photos/seed/upcoming-206/600/800",
        region: "서울 종로",
        place: "인사동 갤러리",
        startDate: "2026-03-11",
        endDate: "2026-04-02",
        category: ["전시", "사진"],
        dDay: 21,
      },
      {
        id: 207,
        type: "POPUP",
        title: "캐릭터 스토어 팝업",
        subTitle: "굿즈 선공개",
        thumbnail: "https://picsum.photos/seed/upcoming-207/600/800",
        region: "서울 마포",
        place: "합정 메세나폴리스",
        startDate: "2026-03-18",
        endDate: "2026-04-01",
        category: ["팝업", "캐릭터"],
        dDay: 28,
      },
      {
        id: 208,
        type: "EXHIBITION",
        title: "설치미술 기획전",
        subTitle: "사전 예매 오픈",
        thumbnail: "https://picsum.photos/seed/upcoming-208/600/800",
        region: "서울 성동",
        place: "성수 스테이지",
        startDate: "2026-03-20",
        endDate: "2026-04-15",
        category: ["전시", "설치미술"],
        dDay: 30,
      },
      {
        id: 209,
        type: "POPUP",
        title: "테크 쇼케이스 팝업",
        subTitle: "사전 체험 신청",
        thumbnail: "https://picsum.photos/seed/upcoming-209/600/800",
        region: "서울 송파",
        place: "잠실 롯데몰",
        startDate: "2026-03-22",
        endDate: "2026-04-05",
        category: ["팝업", "테크"],
        dDay: 32,
      },
      {
        id: 210,
        type: "EXHIBITION",
        title: "조각의 시간",
        subTitle: "프리뷰 전시",
        thumbnail: "https://picsum.photos/seed/upcoming-210/600/800",
        region: "서울 서초",
        place: "한가람미술관",
        startDate: "2026-03-25",
        endDate: "2026-04-20",
        category: ["전시", "조각"],
        dDay: 35,
      },
    ],
    freeCurations: [
      {
        id: 301,
        type: "EXHIBITION",
        title: "무료 전시: 그래픽 아트",
        subTitle: "입장료 0원",
        thumbnail: "https://picsum.photos/seed/free-301/600/800",
        region: "서울 마포",
        place: "홍대 상상마당",
        startDate: "2026-02-12",
        endDate: "2026-03-02",
        category: ["전시", "디자인"],
        dDay: 12,
      },
      {
        id: 302,
        type: "POPUP",
        title: "무료 체험 팝업",
        subTitle: "참여형 이벤트",
        thumbnail: "https://picsum.photos/seed/free-302/600/800",
        region: "서울 송파",
        place: "롯데월드몰",
        startDate: "2026-02-16",
        endDate: "2026-03-05",
        category: ["팝업", "테크"],
        dDay: 15,
      },
      {
        id: 303,
        type: "EXHIBITION",
        title: "무료 사진전: 서울의 밤",
        subTitle: "야간 관람",
        thumbnail: "https://picsum.photos/seed/free-303/600/800",
        region: "서울 종로",
        place: "북촌 갤러리",
        startDate: "2026-02-20",
        endDate: "2026-03-08",
        category: ["전시", "사진"],
        dDay: 18,
      },
      {
        id: 304,
        type: "POPUP",
        title: "무료 굿즈 체험존",
        subTitle: "선착순 증정",
        thumbnail: "https://picsum.photos/seed/free-304/600/800",
        region: "서울 영등포",
        place: "더현대 서울",
        startDate: "2026-02-21",
        endDate: "2026-03-06",
        category: ["팝업", "캐릭터"],
        dDay: 16,
      },
      {
        id: 305,
        type: "EXHIBITION",
        title: "무료 전시: 도시 스케치",
        subTitle: "주말 한정",
        thumbnail: "https://picsum.photos/seed/free-305/600/800",
        region: "서울 마포",
        place: "서교 갤러리",
        startDate: "2026-02-22",
        endDate: "2026-03-09",
        category: ["전시", "드로잉"],
        dDay: 19,
      },
      {
        id: 306,
        type: "POPUP",
        title: "무료 음료 팝업",
        subTitle: "시음 이벤트",
        thumbnail: "https://picsum.photos/seed/free-306/600/800",
        region: "서울 강남",
        place: "코엑스",
        startDate: "2026-02-23",
        endDate: "2026-03-04",
        category: ["팝업", "F&B"],
        dDay: 14,
      },
      {
        id: 307,
        type: "EXHIBITION",
        title: "무료 전시: 아트 포스터",
        subTitle: "입장 무료",
        thumbnail: "https://picsum.photos/seed/free-307/600/800",
        region: "서울 성동",
        place: "성수 갤러리",
        startDate: "2026-02-24",
        endDate: "2026-03-10",
        category: ["전시", "그래픽"],
        dDay: 20,
      },
      {
        id: 308,
        type: "POPUP",
        title: "무료 키링 팝업",
        subTitle: "포토존 이벤트",
        thumbnail: "https://picsum.photos/seed/free-308/600/800",
        region: "서울 마포",
        place: "합정 카페거리",
        startDate: "2026-02-24",
        endDate: "2026-03-07",
        category: ["팝업", "라이프스타일"],
        dDay: 17,
      },
      {
        id: 309,
        type: "EXHIBITION",
        title: "무료 사진전: 빛의 공간",
        subTitle: "가벼운 산책 전시",
        thumbnail: "https://picsum.photos/seed/free-309/600/800",
        region: "서울 종로",
        place: "삼청동 갤러리",
        startDate: "2026-02-25",
        endDate: "2026-03-14",
        category: ["전시", "사진"],
        dDay: 24,
      },
      {
        id: 310,
        type: "POPUP",
        title: "무료 체험존: 홈리빙",
        subTitle: "체험 선착순",
        thumbnail: "https://picsum.photos/seed/free-310/600/800",
        region: "서울 서초",
        place: "고속터미널",
        startDate: "2026-02-26",
        endDate: "2026-03-12",
        category: ["팝업", "라이프스타일"],
        dDay: 22,
      },
    ],
    todayOpenCurations: [
      {
        id: 401,
        type: "POPUP",
        title: "오늘 오픈! 스니커 팝업",
        subTitle: "신상 런칭",
        thumbnail: "https://picsum.photos/seed/today-401/600/800",
        region: "서울 잠실",
        place: "잠실 롯데월드몰",
        startDate: "2026-02-18",
        endDate: "2026-03-05",
        category: ["팝업", "패션"],
        dDay: 15,
      },
      {
        id: 402,
        type: "EXHIBITION",
        title: "오늘 오픈 전시: 일러스트",
        subTitle: "신규 전시",
        thumbnail: "https://picsum.photos/seed/today-402/600/800",
        region: "서울 성동",
        place: "성수 아트홀",
        startDate: "2026-02-18",
        endDate: "2026-03-18",
        category: ["전시", "일러스트"],
        dDay: 28,
      },
      {
        id: 403,
        type: "POPUP",
        title: "오늘 오픈! 푸드 마켓",
        subTitle: "한정 메뉴 공개",
        thumbnail: "https://picsum.photos/seed/today-403/600/800",
        region: "서울 마포",
        place: "연남동 거리",
        startDate: "2026-02-18",
        endDate: "2026-03-04",
        category: ["팝업", "F&B"],
        dDay: 14,
      },
      {
        id: 404,
        type: "EXHIBITION",
        title: "오늘 오픈 전시: 회화",
        subTitle: "작가전",
        thumbnail: "https://picsum.photos/seed/today-404/600/800",
        region: "서울 서대문",
        place: "홍제천 갤러리",
        startDate: "2026-02-18",
        endDate: "2026-03-22",
        category: ["전시", "회화"],
        dDay: 32,
      },
      {
        id: 405,
        type: "POPUP",
        title: "오늘 오픈! 뷰티 체험",
        subTitle: "스킨케어 라인 런칭",
        thumbnail: "https://picsum.photos/seed/today-405/600/800",
        region: "서울 강남",
        place: "가로수길",
        startDate: "2026-02-18",
        endDate: "2026-03-08",
        category: ["팝업", "뷰티"],
        dDay: 18,
      },
      {
        id: 406,
        type: "EXHIBITION",
        title: "오늘 오픈 전시: 조각",
        subTitle: "현대 조각 특별전",
        thumbnail: "https://picsum.photos/seed/today-406/600/800",
        region: "서울 용산",
        place: "아트센터",
        startDate: "2026-02-18",
        endDate: "2026-03-20",
        category: ["전시", "조각"],
        dDay: 30,
      },
      {
        id: 407,
        type: "POPUP",
        title: "오늘 오픈! 테크 팝업",
        subTitle: "체험형 쇼룸",
        thumbnail: "https://picsum.photos/seed/today-407/600/800",
        region: "서울 성동",
        place: "성수 연무장길",
        startDate: "2026-02-18",
        endDate: "2026-03-06",
        category: ["팝업", "테크"],
        dDay: 16,
      },
      {
        id: 408,
        type: "EXHIBITION",
        title: "오늘 오픈 전시: 사진",
        subTitle: "신규 기획전",
        thumbnail: "https://picsum.photos/seed/today-408/600/800",
        region: "서울 종로",
        place: "인사동 아트홀",
        startDate: "2026-02-18",
        endDate: "2026-03-25",
        category: ["전시", "사진"],
        dDay: 35,
      },
      {
        id: 409,
        type: "POPUP",
        title: "오늘 오픈! 라이프 팝업",
        subTitle: "홈&리빙 셀렉션",
        thumbnail: "https://picsum.photos/seed/today-409/600/800",
        region: "서울 마포",
        place: "상수동",
        startDate: "2026-02-18",
        endDate: "2026-03-09",
        category: ["팝업", "라이프스타일"],
        dDay: 19,
      },
      {
        id: 410,
        type: "EXHIBITION",
        title: "오늘 오픈 전시: 디자인",
        subTitle: "그래픽 실험",
        thumbnail: "https://picsum.photos/seed/today-410/600/800",
        region: "서울 중구",
        place: "DDP",
        startDate: "2026-02-18",
        endDate: "2026-03-28",
        category: ["전시", "디자인"],
        dDay: 38,
      },
    ],
  },
};

const MOCK_POPULAR: PopularResponse = {
  result: "SUCCESS",
  data: {
    popup: {
      daily: [
        {
          rank: 1,
          id: 901,
          title: "브랜드 팝업 스토어",
          thumbnail: "https://picsum.photos/seed/pop-daily-901/400/560",
          address: "서울 성수",
          period: "2026.02.10 - 2026.02.28",
        },
        {
          rank: 2,
          id: 902,
          title: "캐릭터 굿즈 팝업",
          thumbnail: "https://picsum.photos/seed/pop-daily-902/400/560",
          address: "서울 홍대",
          period: "2026.02.12 - 2026.03.01",
        },
        {
          rank: 3,
          id: 903,
          title: "뷰티 체험 팝업",
          thumbnail: "https://picsum.photos/seed/pop-daily-903/400/560",
          address: "서울 강남",
          period: "2026.02.15 - 2026.03.05",
        },
      ],
      weekly: [
        {
          rank: 1,
          id: 904,
          title: "라이프스타일 팝업",
          thumbnail: "https://picsum.photos/seed/pop-week-904/400/560",
          address: "서울 성수",
          period: "2026.02.01 - 2026.02.20",
        },
        {
          rank: 2,
          id: 905,
          title: "테크 체험 팝업",
          thumbnail: "https://picsum.photos/seed/pop-week-905/400/560",
          address: "서울 송파",
          period: "2026.02.08 - 2026.02.25",
        },
        {
          rank: 3,
          id: 906,
          title: "푸드 팝업 마켓",
          thumbnail: "https://picsum.photos/seed/pop-week-906/400/560",
          address: "서울 마포",
          period: "2026.02.05 - 2026.02.22",
        },
      ],
      monthly: [
        {
          rank: 1,
          id: 907,
          title: "대형 브랜드 팝업",
          thumbnail: "https://picsum.photos/seed/pop-month-907/400/560",
          address: "서울 강남",
          period: "2026.02.01 - 2026.02.28",
        },
        {
          rank: 2,
          id: 908,
          title: "캐릭터 팝업 페어",
          thumbnail: "https://picsum.photos/seed/pop-month-908/400/560",
          address: "서울 용산",
          period: "2026.02.03 - 2026.02.27",
        },
        {
          rank: 3,
          id: 909,
          title: "패션 팝업 위크",
          thumbnail: "https://picsum.photos/seed/pop-month-909/400/560",
          address: "서울 성수",
          period: "2026.02.06 - 2026.03.02",
        },
      ],
    },
    exhibition: {
      daily: [
        {
          rank: 1,
          id: 951,
          title: "현대미술 특별전",
          thumbnail: "https://picsum.photos/seed/exh-daily-951/400/560",
          address: "서울 종로",
          period: "2026.02.01 - 2026.03.10",
        },
        {
          rank: 2,
          id: 952,
          title: "사진전: 도시의 순간",
          thumbnail: "https://picsum.photos/seed/exh-daily-952/400/560",
          address: "서울 용산",
          period: "2026.02.05 - 2026.03.12",
        },
        {
          rank: 3,
          id: 953,
          title: "일러스트 기획전",
          thumbnail: "https://picsum.photos/seed/exh-daily-953/400/560",
          address: "서울 마포",
          period: "2026.02.07 - 2026.03.08",
        },
      ],
      weekly: [
        {
          rank: 1,
          id: 954,
          title: "디자인 아카이브전",
          thumbnail: "https://picsum.photos/seed/exh-week-954/400/560",
          address: "서울 성동",
          period: "2026.02.02 - 2026.03.20",
        },
        {
          rank: 2,
          id: 955,
          title: "조각의 흐름전",
          thumbnail: "https://picsum.photos/seed/exh-week-955/400/560",
          address: "서울 서초",
          period: "2026.02.10 - 2026.03.30",
        },
        {
          rank: 3,
          id: 956,
          title: "설치미술전",
          thumbnail: "https://picsum.photos/seed/exh-week-956/400/560",
          address: "서울 강남",
          period: "2026.02.12 - 2026.03.25",
        },
      ],
      monthly: [
        {
          rank: 1,
          id: 957,
          title: "사진 아트 페스티벌",
          thumbnail: "https://picsum.photos/seed/exh-month-957/400/560",
          address: "서울 용산",
          period: "2026.02.01 - 2026.03.31",
        },
        {
          rank: 2,
          id: 958,
          title: "현대미술 컬렉션",
          thumbnail: "https://picsum.photos/seed/exh-month-958/400/560",
          address: "서울 종로",
          period: "2026.02.03 - 2026.03.28",
        },
        {
          rank: 3,
          id: 959,
          title: "일러스트 페어",
          thumbnail: "https://picsum.photos/seed/exh-month-959/400/560",
          address: "서울 마포",
          period: "2026.02.06 - 2026.03.22",
        },
      ],
    },
  },
};

export async function getMain() {
  if (USE_MOCK_MAIN) return MOCK_MAIN;
  const response = await axiosInstance.get<MainResponse>("/main");
  return response.data;
}

export async function getPopular(limit: number = 10) {
  if (USE_MOCK_MAIN) return MOCK_POPULAR;
  const response = await axiosInstance.get<PopularResponse>(
    "/main/popular",
    { params: { limit } }
  );
  return response.data;
}
